name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
 
    - name: dotnet build
      run: dotnet build TicTacToe.sln -c Release
    
    - name: Run automated unit and integration tests
      run: dotnet test -c Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput="${{ github.workspace }}/coverage/lcov.info" /p:ExcludeByFile=\"/TicTacToeAPI/Program.cs\"
      # /p:MergeWith="${{ github.workspace }}/coverage/lcov.info" 
      
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{ github.workspace }}/coverage/lcov.info